version: "3.3"

services:
  petshop:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: petshop
    restart: always
    command: bash -c "python manage.py runserver 34.122.112.135:7321"
    volumes:
      - .:/petshop
    ports:
      - "7321:7321"
